added subnet,auto update,slack args

diff --git a/databricks/kubiya/tools/terraform-db-apply-azure.yaml b/databricks/kubiya/tools/terraform-db-apply-azure.yaml
--- a/databricks/kubiya/tools/terraform-db-apply-azure.yaml
+++ b/databricks/kubiya/tools/terraform-db-apply-azure.yaml
@@ -32,41 +32,51 @@ tools:
       -var "enhanced_monitoring_enabled={{ .enhanced_monitoring_enabled }}" \
       -var "azure_client_id=${ARM_CLIENT_ID}" \
       -var "azure_client_secret=${ARM_CLIENT_SECRET}" \
-      -var "azure_tenant_id=${ARM_TENANT_ID}" 
+      -var "azure_tenant_id=${ARM_TENANT_ID}" \
+      -var "address_space={{ .address_space }}" \
+      -var "address_prefixes_public={{ .address_prefixes_public }}" \
+      -var "address_prefixes_private={{ .address_prefixes_private }}" \
+      -var "automatic_update={{ .automatic_update }}" \
+      -var "restart_no_updates={{ .restart_no_updates }}" \
+      -var "day_of_week={{ .day_of_week }}" \
+      -var "frequency={{ .frequency }}" \
+      -var "hours={{ .hours }}" \
+      -var "minutes={{ .minutes }}"
+
       
-    echo "The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob"      
-    echo "The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview"                             
+    # echo "The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob"      
+    # echo "The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview"                             
     
     # write your message here
 
 
-    # MESSAGE=$(cat <<EOF
-    # The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob
-    # The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview
-    # EOF
-    # )
+    MESSAGE=$(cat <<EOF
+    The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob
+    The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview
+    EOF
+    )
 
-    # # Ensure required environment variables are set
-    # if [ -z "$SLACK_CHANNEL_ID" ] || [ -z "$SLACK_THREAD_TS" ] || [ -z "$SLACK_API_KEY" ]; then
-    #   echo "Error: SLACK_CHANNEL_ID, SLACK_THREAD_TS, and SLACK_API_KEY must be set."
-    #   exit 1
-    # fi
+    # Ensure required environment variables are set
+    if [ -z "$SLACK_CHANNEL_ID" ] || [ -z "$SLACK_THREAD_TS" ] || [ -z "$SLACK_API_KEY" ]; then
+      echo "Error: SLACK_CHANNEL_ID, SLACK_THREAD_TS, and SLACK_API_KEY must be set."
+      exit 1
+    fi
 
-    # # Prepare the payload for sending a multiline message in a thread
-    # PAYLOAD=$(cat <<EOF
-    # {
-    #     "channel": "$SLACK_CHANNEL_ID",
-    #     "text": "$MESSAGE",
-    #     "thread_ts": "$SLACK_THREAD_TS"
-    # }
-    # EOF
-    # )
+    # Prepare the payload for sending a multiline message in a thread
+    PAYLOAD=$(cat <<EOF
+    {
+        "channel": "$SLACK_CHANNEL_ID",
+        "text": "$MESSAGE",
+        "thread_ts": "$SLACK_THREAD_TS"
+    }
+    EOF
+    )
 
-    # # Send the message using Slack API
-    # curl -X POST "https://slack.com/api/chat.postMessage" \
-    # -H "Authorization: Bearer $SLACK_API_KEY" \
-    # -H "Content-Type: application/json" \
-    # --data "$PAYLOAD"
+    # Send the message using Slack API
+    curl -X POST "https://slack.com/api/chat.postMessage" \
+    -H "Authorization: Bearer $SLACK_API_KEY" \
+    -H "Content-Type: application/json" \
+    --data "$PAYLOAD"
 
   args:
     - name: "workspace_name"
@@ -144,8 +154,43 @@ tools:
       description: "The ID of the private subnet network security group association."
       required: false  
 
-  
+    - name: "address_space"
+      description: "The address space to be used for the virtual network."
+      required: false
 
+    - name: "address_prefixes_public"
+      description: "The address prefix for the public network."
+      required: false
+    
+    - name: "address_prefixes_private"
+      description: "The address prefix for the private network."
+      required: false
+
+    - name: "automatic_update"
+      description: "Enable automatic update."
+      required: false
+      default: false
+
+    - name: "restart_no_updates"
+      description: "Enable restart even if there are no updates."
+      required: false
+      default: false
+
+    - name: "day_of_week"
+      description: "Day of the week to apply updates."
+      required: false
+    
+    - name: "frequency"
+      description: "Frequency of updates."
+      required: false
+
+    - name: "hours"
+      description: "Hours of window start time."
+      required: false
+    
+    - name: "minutes"
+      description: "Minutes of window start time."
+      required: false
   env:
     - "DB_ACCOUNT_ID"
     - "DB_ACCOUNT_CLIENT_ID"
