added db resource args, no slack

diff --git a/databricks/kubiya/tools/terraform-db-apply-azure.yaml b/databricks/kubiya/tools/terraform-db-apply-azure.yaml
--- a/databricks/kubiya/tools/terraform-db-apply-azure.yaml
+++ b/databricks/kubiya/tools/terraform-db-apply-azure.yaml
@@ -27,38 +27,44 @@ tools:
       -var "public_subnet_name={{ .public_subnet_name }}" \
       -var "public_subnet_network_security_group_association_id={{ .public_subnet_network_security_group_association_id }}" \
       -var "private_subnet_network_security_group_association_id={{ .private_subnet_network_security_group_association_id }}" \
-      -var "storage_account_name={{ .storage_account_name }}" 
+      -var "storage_account_name={{ .storage_account_name }}" \
+      -var "security_profile_enabled={{ .security_profile_enabled }}" \
+      -var "enhanced_monitoring_enabled={{ .enhanced_monitoring_enabled }}" 
       
-    # echo "The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob"      
-    # echo "The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview"                             
-    MESSAGE=$(cat <<EOF
-    The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob
-    The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview
-    EOF
-    )
-
-    # Ensure required environment variables are set
-    if [ -z "$SLACK_CHANNEL_ID" ] || [ -z "$SLACK_THREAD_TS" ] || [ -z "$SLACK_API_KEY" ]; then
-      echo "Error: SLACK_CHANNEL_ID, SLACK_THREAD_TS, and SLACK_API_KEY must be set."
-      exit 1
-    fi
-
-    # Prepare the payload for sending a multiline message in a thread
-    PAYLOAD=$(cat <<EOF
-    {
-        "channel": "$SLACK_CHANNEL_ID",
-        "text": "$MESSAGE",
-        "thread_ts": "$SLACK_THREAD_TS"
-    }
-    EOF
-    )
-
-    # Send the message using Slack API
-    curl -X POST "https://slack.com/api/chat.postMessage" \
-    -H "Authorization: Bearer $SLACK_API_KEY" \
-    -H "Content-Type: application/json" \
-    --data "$PAYLOAD"
+    echo "The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob"      
+    echo "The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview"                             
     
+    # write your message here
+
+
+    # MESSAGE=$(cat <<EOF
+    # The state file can be found here: https://mytestbackendaccount.blob.core.windows.net/mytestbackendblob
+    # The workspace can be found here: https://portal.azure.com/#@kubiya.ai/resource/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/databricks-{{ .workspace_name }}-rg/providers/Microsoft.Databricks/workspaces/databricks-{{ .workspace_name }}-workspace/overview
+    # EOF
+    # )
+
+    # # Ensure required environment variables are set
+    # if [ -z "$SLACK_CHANNEL_ID" ] || [ -z "$SLACK_THREAD_TS" ] || [ -z "$SLACK_API_KEY" ]; then
+    #   echo "Error: SLACK_CHANNEL_ID, SLACK_THREAD_TS, and SLACK_API_KEY must be set."
+    #   exit 1
+    # fi
+
+    # # Prepare the payload for sending a multiline message in a thread
+    # PAYLOAD=$(cat <<EOF
+    # {
+    #     "channel": "$SLACK_CHANNEL_ID",
+    #     "text": "$MESSAGE",
+    #     "thread_ts": "$SLACK_THREAD_TS"
+    # }
+    # EOF
+    # )
+
+    # # Send the message using Slack API
+    # curl -X POST "https://slack.com/api/chat.postMessage" \
+    # -H "Authorization: Bearer $SLACK_API_KEY" \
+    # -H "Content-Type: application/json" \
+    # --data "$PAYLOAD"
+
   args:
     - name: "workspace_name"
       description: "The name of the databricks workspace."
@@ -105,6 +111,16 @@ tools:
       required: false
       default: false
 
+    - name: "security_profile_enabled"
+      description: "Enable security profile, boolean, can be true or false."
+      required: false
+      default: false
+
+    - name: "enhanced_monitoring_enabled"
+      description: "Enable enhanced monitoring, boolean, can be true or false."
+      required: false
+      default: false
+
     - name: "virtual_network_id"
       description: "The virtual network id."
       required: false
@@ -142,6 +158,6 @@ tools:
     - "ARM_TENANT_ID"
     - "ARM_SUBSCRIPTION_ID"
     - "PAT"
-    - "SLACK_CHANNEL_ID"
-    - "SLACK_THREAD_TS"
-    - "SLACK_API_KEY"
+    # - "SLACK_CHANNEL_ID"
+    # - "SLACK_THREAD_TS"
+    # - "SLACK_API_KEY"
